# configuration file for production environment

# only log warning and error messsages
log: "warning"

# don't consider warnings critical
warnings: 0

# hide errors
show_errors: 0

# disable server tokens in production environments
no_server_tokens: 1

engines :
    logger :
         LogAny :
             logger   :
                 - JSON
                 - /var/log/ContactMyReps/app.log
